### ISSUE TITLE
Saving HDD Eap Keys saves in C:\ not in the folder with the executable.

### ISSUE THREAD

**Issue by MandaThePanda** [andy-man/ps4-wee-tools#6]
Extra Info:

CMD needs to run as Administrator otherwise it will prompt this error.

 `Using new key blob

 [magic] E5E5E501
 [ICC NVS] magic is OK
 [eap_hdd_wrapped_key] length 40
 [smi_version] -1 FFFFFFFF
 [eap_hdd_key_blob] check
 [unwrap eap hdd]
 [eap hdd unwrapped]

 XTS data key:  KEY
 XTS tweak key:  KEY

Traceback (most recent call last):
  File "ps4-wee-tools.py", line 25, in <module>
  File "ps4-wee-tools.py", line 19, in main
  File "tools\Tools.py", line 33, in screenFileSelect
  File "tools\Tools.py", line 21, in launchTool
  File "tools\NorTools.py", line 299, in screenNorTools
  File "tools\NorTools.py", line 333, in screenAdditionalTools
  File "tools\NorTools.py", line 329, in screenAdditionalTools
  File "tools\NorTools.py", line 344, in screenHddKey
  File "utils\hdd_eap.py", line 138, in getHddEapKey
PermissionError: [Errno 13] Permission denied: '\\keys.bin'
[43752] Failed to execute script 'ps4-wee-tools' due to unhandled exception!`

**Comment by andy-man** [comment]
Programm intends to output keys.bin near dump file and not in app's folder.
Anyway more info is required 
(py or exe, app version, windows version, path to app, path to dump)
How do you launch it? (bat file / from cmd / by drag-n-drop dump to app)

**Comment by MandaThePanda** [comment]
Im running via CMD.

**Comment by andy-man** [comment]
I've tested with v0.8 and didn't get such error. However if someone get such error message, should try to launch app as Administrator.
